/root/PayBot/src/controller/document.py:55: RuntimeWarning: coroutine 'Message.reply_text' was never awaited
  update.message.reply_text(f'Файл был отправлен пользователю')
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Подключение к базе данных успешно
[-4181748266, 1194700554, 611660794]
Message sent successfully
-4181748266
Проверяем, существет ли пользователь 1194700554
Пользователь с таким chat_id уже существует
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT * FROM orders WHERE status = 'active'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
UPDATE users SET state = 'change_course' WHERE chat_id = '-4181748266'
 State usera обновлен
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
UPDATE users SET state = '' WHERE chat_id = '-4181748266'
 State usera обновлен
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
SELECT state FROM users WHERE chat_id = '-4181748266'
5595592521
Проверяем, существет ли пользователь 5595592521
Новый пользователь добавлен
UPDATE users SET state = 'await_sum' WHERE chat_id = '5595592521'
 State usera обновлен
SELECT state FROM users WHERE chat_id = '5595592521'
False
INSERT INTO orders (id, ids, username, chat_id, sum, course, profit, marje, date, state, status, timechk) VALUES (4, '0c118202-60b6-4119-86ee-4c1fb4d28197','Marllosh', '5595592521', 2472.53, 91.98432, 264.91, 1.12, '2024-05-16 11:41:23.933669', 'query', 'request', 'start')
Заказ создан
UPDATE orders SET state = 'request', status='request' WHERE chat_id = '5595592521', state = 'query'
Error: syntax error at or near ","
LINE 1: ...st', status='request' WHERE chat_id = '5595592521', state = ...
                                                             ^

SELECT ids FROM orders WHERE chat_id = '5595592521' AND state = 'query'
SELECT sum FROM orders WHERE chat_id = '5595592521'
UPDATE orders SET state = 'await_recipt' WHERE ids = '0c118202-60b6-4119-86ee-4c1fb4d28197'
Квитанция принята
UPDATE users SET state = 'await_recipt' WHERE chat_id = '611660794'
 State usera обновлен
UPDATE orders SET status = 'active' WHERE ids = '0c118202-60b6-4119-86ee-4c1fb4d28197'
Статус заказа изменен на:  active
UPDATE orders SET date = '2024-05-16 11:41:44.682907' WHERE ids = '0c118202-60b6-4119-86ee-4c1fb4d28197'
Время заказа изменен на:  2024-05-16 11:41:44.682907
SELECT chat_id FROM orders WHERE ids = '0c118202-60b6-4119-86ee-4c1fb4d28197'
UPDATE users SET state = 'await_email_url' WHERE chat_id = '5595592521'
 State usera обновлен
Время проверки изменено
UPDATE orders SET state = 'apply_recipt' WHERE ids = '0c118202-60b6-4119-86ee-4c1fb4d28197'
Квитанция принята
SELECT chat_id FROM orders WHERE ids = '0c118202-60b6-4119-86ee-4c1fb4d28197'
UPDATE users SET state = 'await_email_url' WHERE chat_id = '5595592521'
 State usera обновлен
SELECT state FROM users WHERE chat_id = '5595592521'
UPDATE orders SET email = 'Nep@gmail.com', url = 'https://youtu.be/v9WYGUBX6OY?si=4RLPwX9QOyOtp_rE' WHERE chat_id = '5595592521' AND status = 'active'
email and url занесены в БД
UPDATE users SET state = 'await_close_order' WHERE chat_id = '5595592521'
 State usera обновлен
SELECT chat_id FROM orders WHERE ids = '0c118202-60b6-4119-86ee-4c1fb4d28197'
UPDATE users SET state = 'order_complete' WHERE chat_id = '5595592521'
 State usera обновлен
UPDATE orders SET state = 'order_complete' WHERE ids = '0c118202-60b6-4119-86ee-4c1fb4d28197'
Квитанция принята
UPDATE orders SET status = 'complete' WHERE ids = '0c118202-60b6-4119-86ee-4c1fb4d28197'
Статус заказа изменен на:  complete
SELECT state FROM users WHERE chat_id = '5595592521'
False
INSERT INTO orders (id, ids, username, chat_id, sum, course, profit, marje, date, state, status, timechk) VALUES (5, '75919d8d-e3dd-4cef-9d64-92ecb20cac86','Marllosh', '5595592521', 1030.22, 91.98432, 110.38, 1.12, '2024-05-16 11:45:23.994557', 'query', 'request', 'start')
Заказ создан
UPDATE orders SET state = 'request', status='request' WHERE chat_id = '5595592521', state = 'query'
Error: syntax error at or near ","
LINE 1: ...st', status='request' WHERE chat_id = '5595592521', state = ...
                                                             ^

SELECT ids FROM orders WHERE chat_id = '5595592521' AND state = 'query'
SELECT sum FROM orders WHERE chat_id = '5595592521'
UPDATE orders SET state = 'await_recipt' WHERE ids = '75919d8d-e3dd-4cef-9d64-92ecb20cac86'
Квитанция принята
UPDATE users SET state = 'await_recipt' WHERE chat_id = '611660794'
 State usera обновлен
UPDATE orders SET status = 'active' WHERE ids = '75919d8d-e3dd-4cef-9d64-92ecb20cac86'
Статус заказа изменен на:  active
UPDATE orders SET date = '2024-05-16 11:45:37.969080' WHERE ids = '75919d8d-e3dd-4cef-9d64-92ecb20cac86'
Время заказа изменен на:  2024-05-16 11:45:37.969080
SELECT chat_id FROM orders WHERE ids = '75919d8d-e3dd-4cef-9d64-92ecb20cac86'
UPDATE users SET state = 'await_email_url' WHERE chat_id = '5595592521'
 State usera обновлен
Время проверки изменено
UPDATE orders SET state = 'apply_recipt' WHERE ids = '75919d8d-e3dd-4cef-9d64-92ecb20cac86'
Квитанция принята
SELECT chat_id FROM orders WHERE ids = '75919d8d-e3dd-4cef-9d64-92ecb20cac86'
/root/PayBot/src/controller/photo.py:59: RuntimeWarning: coroutine 'Message.reply_text' was never awaited
  update.message.reply_text(f'Файл был отправлен пользователю')
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py", line 1277, in process_update
    await coroutine
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
  File "/root/PayBot/src/controller/message.py", line 70, in handle_message
    summ = round((int(txt) * usd),2)
ValueError: invalid literal for int() with base 10: 'Ввести свою сумму'
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py", line 1277, in process_update
    await coroutine
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
  File "/root/PayBot/src/controller/button.py", line 102, in button_callback
    file_name = query.message.document.file_name
AttributeError: 'NoneType' object has no attribute 'file_name'
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py", line 1277, in process_update
    await coroutine
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
  File "/root/PayBot/src/controller/button.py", line 102, in button_callback
    file_name = query.message.document.file_name
AttributeError: 'NoneType' object has no attribute 'file_name'
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py", line 1277, in process_update
    await coroutine
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
  File "/root/PayBot/src/controller/button.py", line 102, in button_callback
    file_name = query.message.document.file_name
AttributeError: 'NoneType' object has no attribute 'file_name'
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py", line 1277, in process_update
    await coroutine
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
  File "/root/PayBot/src/controller/button.py", line 102, in button_callback
    file_name = query.message.document.file_name
AttributeError: 'NoneType' object has no attribute 'file_name'
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py", line 1277, in process_update
    await coroutine
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
  File "/root/PayBot/src/controller/button.py", line 102, in button_callback
    file_name = query.message.document.file_name
AttributeError: 'NoneType' object has no attribute 'file_name'
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py", line 1277, in process_update
    await coroutine
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
  File "/root/PayBot/src/controller/button.py", line 102, in button_callback
    file_name = query.message.document.file_name
AttributeError: 'NoneType' object has no attribute 'file_name'
